layout_spectrum: 0.4535305
color:
  saturation: 0.7827194
  lightness: 0.7226717
  brandStrength: 0.7437276
  brandColors:
    - '#272D39'
    - '#FFFFFF'
    - '#C7B99F'
    - '#6493D7'
    - '#6B6764'
  rhythmicContrast: 0.4719265
typography_spectrum: 0.7150537
name: 'Paragon Renovations '
